mysql:
  #  path: '127.0.0.1:3306'
  config: 'charset=utf8mb4&parseTime=True&loc=Local'
  db-name: 'qmPlus'
  password: "OmLgjkxS9l(6Ck"
  path: "47.98.141.227:3306"
  username: 'root'
  #  password: '123456'
  max-idle-conns: 10
  max-open-conns: 10
  log-mode: false
